import SwiftUI

/// A natural-language briefing of the day, generated by Apple's on-device
/// Foundation Models LLM. Sits on the Today screen under the readiness gauge.
/// Generation happens on-device via ``AICoach``; while it runs we show a gentle
/// "thinking" state, and when the model isn't available we explain why instead
/// of hiding the feature entirely.
struct AICoachCard: View {
    let readiness: ReadinessScore
    let snapshot: AdaptiveIntelligenceSnapshot
    let plan: AdvisorPlan?
    /// The athlete's chosen goal, if any. nil → general endurance advice.
    let goal: Goal?

    @State private var phase: Phase = .idle
    /// Stamp of (scoreDate, goal) we last produced a briefing for — added to
    /// the cache key so changing the goal in Settings re-prompts the model.
    @State private var generatedForKey: String?

    enum Phase: Equatable {
        case idle
        case generating
        case ready(headline: String, guidance: String, focus: String)
        case unavailable(String)
        case failed
    }

    /// Date + goal compose into one cache key — change either and the briefing
    /// regenerates.
    private var taskKey: String {
        "\(snapshot.scoreDate.timeIntervalSince1970)|\(goal?.rawValue ?? "none")"
    }

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            header
            content
        }
        .padding(20)
        .frame(maxWidth: .infinity, alignment: .leading)
        .background(.thinMaterial, in: RoundedRectangle(cornerRadius: 20))
        .task(id: taskKey) {
            // Don't regenerate if we already have a briefing for this key.
            if generatedForKey == taskKey, case .ready = phase { return }
            await generate()
        }
    }

    private var header: some View {
        HStack(spacing: 8) {
            Label("AI Coach", systemImage: "sparkles")
                .font(.headline)
            Spacer()
            // Manual regenerate. Bypasses the `generatedFor` cache because the
            // user explicitly asked for a fresh take. Disabled mid-generation
            // so a double-tap can't pile up parallel model calls.
            Button {
                Task { await generate() }
            } label: {
                Image(systemName: "arrow.clockwise")
                    .font(.caption.weight(.semibold))
                    .foregroundStyle(.secondary)
                    .padding(8)
                    .background(Color.secondary.opacity(0.12), in: Circle())
            }
            .buttonStyle(.plain)
            .disabled(phase == .generating)
            .accessibilityLabel("Regenerate briefing")
        }
    }

    @ViewBuilder
    private var content: some View {
        switch phase {
        case .idle, .generating:
            HStack(spacing: 10) {
                ProgressView()
                Text("Reading your day…")
                    .font(.subheadline)
                    .foregroundStyle(.secondary)
            }
            .frame(maxWidth: .infinity, alignment: .leading)
            .padding(.vertical, 6)

        case let .ready(headline, guidance, focus):
            VStack(alignment: .leading, spacing: 10) {
                Text(headline)
                    .font(.title3.weight(.semibold))
                    .fixedSize(horizontal: false, vertical: true)
                Text(guidance)
                    .font(.callout)
                    .foregroundStyle(.secondary)
                    .fixedSize(horizontal: false, vertical: true)
                if !focus.isEmpty {
                    Label(focus, systemImage: "target")
                        .font(.subheadline.weight(.medium))
                        .foregroundStyle(Color.accentColor)
                        .padding(.horizontal, 12).padding(.vertical, 8)
                        .background(Color.accentColor.opacity(0.12), in: Capsule())
                }
            }
            .transition(.opacity)

        case let .unavailable(message):
            Text(message)
                .font(.subheadline)
                .foregroundStyle(.secondary)
                .fixedSize(horizontal: false, vertical: true)

        case .failed:
            HStack(spacing: 8) {
                Text("Couldn't generate a briefing this time.")
                    .font(.subheadline)
                    .foregroundStyle(.secondary)
                Button("Retry") { Task { await generate() } }
                    .font(.subheadline.weight(.semibold))
                    .buttonStyle(.plain)
                    .foregroundStyle(Color.accentColor)
            }
        }
    }

    private func generate() async {
        switch AICoach.availability() {
        case .unavailable(let reason):
            withAnimation { phase = .unavailable(reason.message) }
            return
        case .available:
            break
        }

        withAnimation { phase = .generating }
        guard #available(iOS 26.0, *) else {
            withAnimation { phase = .unavailable(AICoach.Unavailable.unsupportedOS.message) }
            return
        }
        do {
            let briefing = try await AICoach.briefing(readiness: readiness, snapshot: snapshot, plan: plan, goal: goal)
            generatedForKey = taskKey
            withAnimation {
                phase = .ready(headline: briefing.headline,
                               guidance: briefing.guidance,
                               focus: briefing.focus)
            }
        } catch {
            withAnimation { phase = .failed }
        }
    }
}
